// Builds supabase/seed.sql from the demo data in web-app/src/data/mockData.ts, so the database starts out with exactly
// what the clickable demo shows. Run from the repo root:
//   node supabase/generate-seed.mjs
// (uses jiti, which ships with the web-app's dev dependencies, to load the TypeScript directly)
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(path.join(root, "web-app", "package.json"));
const { createJiti } = require("jiti");
const jiti = createJiti(import.meta.url);

const m = await jiti.import(path.join(root, "web-app", "src", "data", "mockData.ts"));

const q = (v) => (v === null || v === undefined || v === "" ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const s = (v) => `'${String(v ?? "").replace(/'/g, "''")}'`; // never null
const n = (v) => (v === null || v === undefined ? "null" : String(v));
const b = (v) => (v ? "true" : "false");
const arr = (values, type) => `array[${values.join(", ")}]::${type}[]`;

// "2026-09-21 06:00 AM" -> "2026-09-21 06:00"
const toTimestamp = (label) => {
  const [, date, h, min, ap] = label.match(/^(S+) (d+):(d+) (AM|PM)$/);
  return `${date} ${String((Number(h) % 12) + (ap === "PM" ? 12 : 0)).padStart(2, "0")}:${min}`;
};

const userId = new Map(m.teamSeed.map((u) => [u.name, u.id]));
const uid = (name) => {
  const id = userId.get(name);
  if (!id) throw new Error(`Unknown user "${name}" in seed data`);
  return id;
};
const uidOrNull = (name) => (userId.has(name) ? q(userId.get(name)) : "null");
const customerId = new Map(m.customerSeed.map((c) => [c.company, c.id]));
const roleLabel = { super_user: "Super User", management: "Management", account_manager: "Account Manager", assistant: "Assistant", csr: "CSR" };
const rows = (table, columns, values) =>
  values.length ? `insert into public.${table} (${columns.join(", ")}) values\n  ${values.map((v) => `(${v.join(", ")})`).join(",\n  ")};\n\n` : "";

let sql = `-- Demo seed data, generated by supabase/generate-seed.mjs from web-app/src/data/mockData.ts. Do not edit by hand.
-- Intended for a fresh database: re-running it will hit primary-key conflicts.
begin;

`;

// Users and team
sql += rows(
  "app_users",
  ["id", "name", "email", "role", "status"],
  m.teamSeed.map((u) => [q(u.id), q(u.name), q(u.email), q(u.role), q(u.status)]),
);
sql += rows(
  "assistant_supports",
  ["assistant_id", "account_manager_id"],
  m.teamSeed.flatMap((u) => (u.supports ?? []).map((am) => [q(u.id), q(uid(am))])),
);
sql += rows(
  "dashboard_shares",
  ["owner_id", "assistant_id", "shared_at"],
  m.dashboardShareSeed.map((d) => [q(uid(d.owner)), q(uid(d.assistant)), q(d.sharedAt)]),
);

// Settings (mirrors defaultSettings() in DemoDataContext.tsx; API keys are intentionally not stored)
const notifications = {
  "New order issue logged": true,
  "Order Excellence not updated in 24 hours": true,
  "Deal moves to Negotiation": true,
  "Daily sales summary email": false,
  "Sync failure alerts": true,
};
const security = { "Require SSO login": true, "Restrict access to office network": false, "Two-factor authentication": true };
const integrations = {
  "ASI SmartBooks": { method: "Scheduled report to shared drive", schedule: "Daily 6:00 AM", location: "" },
  "Facilis Syncore": { method: "Syncore API v2", schedule: "Nightly 2:00 AM", location: "https://api.syncore.app/v2/orders" },
};
sql += rows(
  "app_settings",
  ["id", "am_project_access", "am_see_all_order_issues", "notifications", "security", "integrations"],
  [["true", "true", "false", `${s(JSON.stringify(notifications))}::jsonb`, `${s(JSON.stringify(security))}::jsonb`, `${s(JSON.stringify(integrations))}::jsonb`]],
);
sql += rows(
  "data_sources",
  ["name", "status", "last_sync", "records_synced", "method"],
  m.dataSources.map((d) => [q(d.name), q(d.status), q(d.lastSync.replace(" AM", ":00").replace(/(\d{2}):(\d{2}):00$/, "$1:$2")), n(d.recordsSynced), q(d.method)]),
);

// CRM
sql += rows(
  "customers",
  ["id", "name", "company", "email", "phone", "total_orders", "lifetime_value", "source", "since", "account_manager_id", "priority", "notes", "weekly_activity_logged", "monthly_activity_logged", "ly_gross_profit"],
  m.customerSeed.map((c) => [q(c.id), q(c.name), q(c.company), q(c.email), q(c.phone), n(c.totalOrders), n(c.lifetimeValue), q(c.source), q(c.since), q(uid(c.accountManager)), q(c.priority), s(c.notes), b(c.weeklyActivityLogged), b(c.monthlyActivityLogged), n(c.lyGrossProfit)]),
);
sql += rows(
  "prospects",
  ["id", "name", "company", "stage", "est_value", "owner_id", "last_contact"],
  m.prospectSeed.map((p) => [q(p.id), q(p.name), q(p.company), q(p.stage), n(p.estValue), q(uid(p.owner)), q(p.lastContact)]),
);
sql += rows(
  "pipeline_deals",
  ["id", "name", "company", "value", "owner_id", "stage", "close_date"],
  m.pipelineDealSeed.map((d) => [q(d.id), q(d.name), q(d.company), n(d.value), q(uid(d.owner)), q(d.stage), q(d.closeDate)]),
);
sql += rows(
  "referral_partners",
  ["id", "name", "contact", "referrals_sent", "conversions", "commission_owed", "status"],
  m.referralPartnerSeed.map((r) => [q(r.id), q(r.name), q(r.contact), n(r.referralsSent), n(r.conversions), n(r.commissionOwed), q(r.status)]),
);

// Budgets
sql += rows(
  "budgets",
  ["id", "rep_id", "fiscal_year", "gp_monthly", "sales_monthly", "notes", "updated_by_id", "updated_at"],
  m.budgetSeed.map((x) => [q(x.id), q(uid(x.rep)), n(x.fiscalYear), x.gp ? arr(x.gp, "numeric") : "null", x.sales ? arr(x.sales, "numeric") : "null", s(x.notes), uidOrNull(x.updatedBy), q(x.updatedAt)]),
);

// Sales orders: FY2026 orders from the demo, plus one order per rep per month for FY2025 so "vs LY" has data.
sql += `insert into public.ingest_batches (source, kind, file_name, status, finished_at) values
  ('ASI SmartBooks', 'sales_orders', 'demo seed', 'succeeded', now()),
  ('Facilis Syncore', 'sales_orders', 'demo seed', 'succeeded', now());

insert into public.sales_orders (order_number, source, invoice_date, customer_name, customer_id, rep_id, amount, cost, status) values
`;
const orderRows = m.salesOrders.map((o) => [s(o.id), q(o.source), q(o.date), s(o.customer), q(customerId.get(o.customer)), q(uid(o.rep)), n(o.amount), n(o.cost), q(o.status)]);
m.repActuals.forEach((r, idx) => {
  r.gp.monthlyLy.forEach((gp, month) => {
    const sales = r.sales.monthlyLy[month];
    const source = (idx + month) % 2 === 0 ? "ASI SmartBooks" : "Facilis Syncore";
    const date = `2025-${String(month + 1).padStart(2, "0")}-15`;
    orderRows.push([s(`SO-25-${idx + 1}-${String(month + 1).padStart(2, "0")}`), q(source), q(date), s("Prior-year total (seed)"), "null", q(uid(r.rep)), n(sales), n(sales - gp), "'paid'"]);
  });
});
sql += `  ${orderRows.map((v) => `(${v.join(", ")})`).join(",\n  ")};\n\n`;
sql += `update public.sales_orders so set ingest_batch_id = (select id from public.ingest_batches ib where ib.file_name = 'demo seed' and ib.source = so.source);
`;
sql += `update public.ingest_batches ib set rows_loaded = (select count(*) from public.sales_orders so where so.ingest_batch_id = ib.id) where file_name = 'demo seed';\n\n`;

// Order Excellence
const issues = m.orderIssueSeed();
sql += rows(
  "order_issues",
  ["id", "order_number", "customer_name", "account_manager_id", "issue_type", "severity", "status", "assigned_to_id", "in_hand_date", "opened_on", "resolved_on", "notes", "updated_by_id", "updated_at"],
  issues.map((i) => [q(i.id), q(i.order), q(i.customer), q(uid(i.accountManager)), q(i.issueType), q(i.severity), q(i.status), uidOrNull(i.assignedTo), q(i.inHandDate), q(i.openedOn), q(i.resolvedOn), s(i.notes), uidOrNull(i.updatedBy), q(i.updatedAt)]),
);

// Project Tracker
sql += rows(
  "project_tracker",
  ["id", "account_name", "account_manager_id", "plan_month", "target_value", "historical_projects", "potential_projects", "status", "notes", "links", "updated_by_id", "updated_at"],
  m.projectTrackerSeed.map((p) => [q(p.id), q(p.accountName), q(uid(p.accountManager)), q(p.month), n(p.targetValue), s(p.historicalProjects), s(p.potentialProjects), q(p.status), s(p.notes), `${s(JSON.stringify(p.links))}::jsonb`, uidOrNull(p.updatedBy), q(p.updatedAt)]),
);

// Audit trail
const roleByName = new Map(m.teamSeed.map((u) => [u.name, roleLabel[u.role]]));
sql += rows(
  "audit_log",
  ["id", "occurred_at", "actor_id", "actor_name", "actor_role", "action", "entity", "details"],
  m.auditLogSeed.map((a) => [q(a.id), q(a.timestamp), q(uid(a.user)), q(a.user), q(roleByName.get(a.user) ?? a.role), q(a.action), q(a.entity), s(a.details)]),
);
sql += `commit;\n`;

writeFileSync(path.join(root, "supabase", "seed.sql"), sql);
console.log(`Wrote supabase/seed.sql (${sql.length} bytes, ${orderRows.length} sales orders)`);
